name: Run buhsu.py with Selenium

on:
  push:
  workflow_dispatch:

jobs:
  run-bushu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run buhsu.py
      run: python buhsu.py

    - name: Upload result screenshot
      uses: actions/upload-artifact@v3
      with:
        name: result-screenshot
        path: result.png






