name: Run buhsu.py with Selenium

on:
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 2 * * *'  # 每天凌晨 2 点运行（UTC）
#
jobs:
  run-bushu:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: 运行 buhsu.py
      run: python buhsu.py
